### ISSUE TITLE
Option to minimize to System Tray on Autostart at Login

### ISSUE THREAD

**Issue by mucke5** [ivpn/desktop-app-ui2#20]
I still don't see an option to enable this feature #7 and it doesn't work in 3.3.7 either.
I am using Ubuntu Budgie (latest LTS).

**Comment by stenya** [comment]
Please, check your settings. Such options have to be enabled:
- Launch at login
- Minimize to tray

![image](https://user-images.githubusercontent.com/7881006/116090087-2d540980-a6ac-11eb-8166-c7cbc40e0827.png)

I just re-tested it on Ubuntu 20.04. It works as expected.
Please, let me know if it helped. Otherwise, I have to install Ubuntu Budgie for testing.

**Comment by stenya** [comment]
Please, ensure also that you are using 'ivpn-ui' package v3.3.7 or newer (the latest version at the current moment is v3.3.10)

**Comment by mucke5** [comment]
@stenya The mere update was not enough. I had to uninstall everything completely and remove remaining files/folders manually.
After the subsequent reinstallation, it now works as desired.
